const Config = {
  spotifyAccessToken: 'BQBlM_bHKugDlK_VtbjIZmaYvJm7-xY8qMPd8BWEr6ZVMZUafwtPQHJ9VOxyPswxiiTo4DtiRLzlNbgxEkHRxA0RC6KtwjGDXt-Se77sfVue2Htusc-uNESZOwbnw8-LmMwF3ZftajHyRA7wqJWrB3azbPTruJe-rKXd9x0HwRTSdzRERqElU6yS2TXs25QMWTHhn9Sb6JqQkAuzoxY1W5dKjTqX8uUwYurhGxi-dYgIFVzfwG-vZcQUOSMW'
}
export default Config
